### ISSUE TITLE
Visualization uses a lot of CPU

### ISSUE THREAD

**Issue by lnostdal** [audiocogs/alac.js#5]
Hi guys,
The first thing people check when looking at the demo is of course CPU use, and at first it seems to be quite high -- but as soon as one minimize the browser window it is low.

I'm guessing this is because of the "silly" visualization?

**Comment by auroranockert** [comment]
Yes, most of the CPU usage is from the visualization, just the audio pipeline takes about 8% of one core on my 2.4GHz Core 2 Duo Macbook Pro using Firefox.

**Comment by lnostdal** [comment]
Yep, about the same here. This kind of ruins the demo though; at least initially. Perhaps it could/should be removed? Anyway, thanks for this; the idea of lossless via the browser is very cool ... :)

**Comment by auroranockert** [comment]
Maybe, we kind of rushed the demo etc. The codec was finished and we didn't want to delay the release.

We're probably going to improve it for our next release. Most of the CPU is spent in drawing, so there is probably a lot of room for improvement.

**Comment by nddrylliog** [comment]
> Yep, about the same here. This kind of ruins the demo though; at least initially. Perhaps it could/should be removed? Anyway, thanks for this; the idea of lossless via the browser is very cool ... :)

@lnostdal You can disable the visualization by clicking on it. Doesn't use any CPU when inactive, so you can (unscientifically) measure the real CPU usage of audio decoding.

**Comment by lnostdal** [comment]
On Fri, Dec 23, 2011 at 5:05 PM, Amos Wenger <
reply@reply.github.com

> wrote:
> 
> > Yep, about the same here. This kind of ruins the demo though; at least
> > initially. Perhaps it could/should be removed? Anyway, thanks for this; the
> > idea of lossless via the browser is very cool ... :)
> 
> @lnostdal You can disable the visualization by clicking on it. Doesn't use
> any CPU when inactive, so you can (unscientifically) measure the real CPU
> usage of audio decoding.

That's odd. I'm sure I tried just that before posting here, but indeed that
works.

**Comment by jussi-kalliokoski** [comment]
You can get the best effect of how cheap the decoding is compared to the UI by first disabling the visualization (it also disables the FFT calculation that way) and going into another tab (doesn't work in Firefox 5 and 8). We'll probably use a WebGL visualization in the future, lifting around 70% of the current CPU load.

But a funny thing is that even the fairly simple UI (excluding the visualization) uses a lot of CPU compared to the actual decoding, because of the DOM manipulation and redrawing of elements (the seek bar, the browser probably renders some surroundings while at it as well).

However, imho, this is an interesting proof that JavaScript is fast (enough), but it's just the all the layers like DOM and canvas slowing things down.
